version: "3.4"

volumes:
  mongo_data:

services:
  # Our MongoDB service:
  mongodb:
    image: mongo:3.6
    ports:
    - published: ${DEMO_MONGO_PORT:-27017}
      target: 27017
    volumes:
    - mongo_data:/data/db

  web:
    image: vovimayhem/real-world-node-express:development
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
    - .:/usr/src
    ports:
    - published: ${DEMO_WEB_PORT:-3000}
      target: 3000
    depends_on:
    - mongodb
    entrypoint: /usr/src/bin/dev-entrypoint
    command: npm run dev
    environment:
      MONGODB_URI: mongodb://mongodb:27017/conduit
